#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <commit-msg-file>" >&2
  exit 2
fi

msg_file="$1"
if [[ ! -f "$msg_file" ]]; then
  echo "commit message file not found: $msg_file" >&2
  exit 2
fi

header="$(sed -n '1p' "$msg_file" | tr -d '\r')"

# Allow merge commits generated by Git.
if [[ "$header" =~ ^Merge\  ]]; then
  exit 0
fi

# Allow fixup/squash commits during local history editing.
if [[ "$header" =~ ^(fixup\!|squash\!)\  ]]; then
  exit 0
fi

if [[ -z "$header" ]]; then
  echo "commit message header is empty" >&2
  exit 1
fi

if (( ${#header} > 100 )); then
  echo "commit header exceeds 100 chars (${#header}): $header" >&2
  exit 1
fi

allowed_types='feat|fix|refactor|perf|docs|test|build|ci|chore|revert'
pattern="^(${allowed_types})\\(([a-z0-9][a-z0-9-]*)\\)(!)?: ([a-z][^.]*)$"

if [[ ! "$header" =~ $pattern ]]; then
  cat >&2 <<'EOF'
invalid commit header format.
expected: <type>(<scope>)!: <subject>
allowed types: feat|fix|refactor|perf|docs|test|build|ci|chore|revert
rules:
- scope is mandatory and uses [a-z0-9-]
- subject starts with lowercase and must not end with '.'
- header length <= 100
EOF
  echo "actual: $header" >&2
  exit 1
fi

type="${BASH_REMATCH[1]}"

# Enforce body templates for change-heavy types.
if [[ "$type" =~ ^(feat|fix|refactor|perf)$ ]]; then
  body="$(tail -n +2 "$msg_file")"
  if ! grep -Eiq '^why: ' <<<"$body"; then
    echo "missing required body line: why: ..." >&2
    exit 1
  fi
  if ! grep -Eiq '^what: ' <<<"$body"; then
    echo "missing required body line: what: ..." >&2
    exit 1
  fi
  if ! grep -Eiq '^impact: ' <<<"$body"; then
    echo "missing required body line: impact: ..." >&2
    exit 1
  fi
fi

exit 0
