# An empty database file is enough: the rows are generated by the query itself, so this
# case exercises querySql and read volume without needing any table or fixture.
addax_duckdb_sql "$E2E_CASE_OUT/big.duckdb" "SELECT 1"
